// <auto-generated />
using System;
using AdventureWorks.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdventureWorks.Repository.Migrations
{
    [DbContext(typeof(AdventureContext))]
    partial class AdventureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AdventureWorks")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdventureWorks.Repository.Model.Competidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Altura");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<decimal>("Peso");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<decimal>("TemperaturaMediaCorpo");

                    b.HasKey("Id");

                    b.ToTable("Competidor");
                });

            modelBuilder.Entity("AdventureWorks.Repository.Model.HistoricoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompetidorId");

                    b.Property<DateTime>("DataCorrida");

                    b.Property<int>("PistaCorridaId");

                    b.Property<decimal>("TempoGasto");

                    b.HasKey("Id");

                    b.HasIndex("CompetidorId");

                    b.HasIndex("PistaCorridaId");

                    b.ToTable("HistoricoCorrida");
                });

            modelBuilder.Entity("AdventureWorks.Repository.Model.PistaCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("PistaCorrida");
                });

            modelBuilder.Entity("AdventureWorks.Repository.Model.HistoricoCorrida", b =>
                {
                    b.HasOne("AdventureWorks.Repository.Model.Competidor", "Competidor")
                        .WithMany("Corridas")
                        .HasForeignKey("CompetidorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AdventureWorks.Repository.Model.PistaCorrida", "PistaCorrida")
                        .WithMany("Corridas")
                        .HasForeignKey("PistaCorridaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
